TryGhost/TrafficAnalytics

compose.yml
no issue
- Adds a `compose.yml` so we can easily run the proxy locally with docker. This should make it easier to ensure we're all running in the same environment, and to make our local environments more similar to the production environment.
=> Added a basic compose.yml for developing in docker

.eslintrc.js, src/app.js, src/utils/query-params.js
no issue
- My commits seem to always have unrelated changes for adding a newline at the end of each file, and for deleting any trailing whitespace on empty lines. Our editors must be configured differently.
- This commit adds rules for these changes to eslint, so it should enforce it the same way for all of us, and not depend on each contributor's editor's configuration.
- These rules should automatically be fixed with `yarn lint --fix`, or if your editor lints on save.
=> Added eslint rules for newlines and trailing spaces

package.json, src/app.js, test/app.test.js, yarn.lock
- We want to move the UA parsing that we currently do in Tinybird into the proxy so we can have more control over it and also to save some processing at query time. Eventually we will parse out the `os`, `browser` and `device` in the proxy and add it to the payload directly.
- This commit adds some basic UA parsing, and outputs the raw data we get from `ua-parser-js` library in the `payload.meta` field, so we can see what kinds of values we get in the real world, without actually changing any of the analytics data just yet. This will help us decide how granular we want to get with each of these fields — i.e. do we want browser versions? Should "Mobile Safari" be the collapsed into "Safari" or not?
=> Added passive UA parsing to proxy

package.json, renovate.json, test/app.test.js, yarn.lock
- The UA parsing library we're using, `[ua-parser-js](https://www.npmjs.com/package/ua-parser-js/v/1.0.40)` switched to an AGPL license starting with version 2.0.0, which we cannot use since this project is MIT licensed. Previous to version 2.0.0, this library is licensed under an MIT license, which means we _can_ use it in this project.
- This commit downgrades the `ua-parser-js` package from `2.0.3` to `1.0.40` to remain in compliance with the license, and adds a renovate rule to prevent automatically upgrading to `^2.x.x`
=> Downgraded `ua-parser-js` library to 1.0.40

package.json, src/app.js, src/services/proxy/index.js, src/services/proxy/processors.js, src/services/proxy/proxy.js, src/services/proxy/validators.js, test/services/proxy/processors.test.js, test/services/proxy/validators.test.js, yarn.lock
Currently this repo is only a simple HTTP proxy server, but eventually it will need to operate in either "http" mode and/or "batch/queue" mode. To make that transition easier in the future, we should decouple the core business logic (validating and processing requests) from the fastify HTTP proxy server.
This comes with the added benefit of making it easier to unit test each step of the processing in isolation, so we can add all the edge cases in fast unit tests, and reserve the E2E tests for high-level smoke tests to cover the basic expected functionality.
This refactor is just a first step in this direction. There's still more to do to fully decouple our core logic from the HTTP interface, but this is a good …
=> Refactored core validation and processing logic into a service

compose.yml
no issue
- The `node_modules` were out of date despite a fresh build, due to an issue with how the volumes were defined in the compose file.
- This change should fix that
=> Fixed node_modules volume in docker compose setup

src/services/proxy/processors.js, test/app.test.js, test/services/proxy/processors.test.js
- Our UA parsing until now has just been logging the raw output from the `ua-parser-js` library, which doesn't return the browser, os and device in the exact format we want it.
- This commit adds some additional processing on top of what `ua-parser-js` gives us. For example, it consolidates "Mobile Safari" and "Safari" into just "Safari".
- It also adds some _very_ basic bot filtering based on a simple regex test on the raw user agent string, similar to what we're doing in Tinybird currently.
- For now, these values are still logged under `payload.meta`, so we can gain more confidence with this running in a passive mode in production with real world user agents.
=> Improved UA parsing for browser, os and device

src/services/proxy/processors.ts, src/types/index.ts, test/app.test.ts, test/services/proxy/processors.test.ts
We've been collecting these fields in the `payload.meta` field for a while to see what kind of data we're getting in the real world. It all looks good to me, so promoting them to top level fields in the payload now.
=> Moved os, browser and device out of the meta key

.github/workflows/build.yml, .github/workflows/deploy.yml
ref PROD-645
ref https://linear.app/ghost/issue/PROD-645/switch-github-actions-to-use-oicd-auth-with-gcp
=> Switch docker push to use OIDC auth

.eslintrc.cjs
no refs
ESlint was throwing some weird errors, like both requiring a semi-colon and not allowing a semi-colon. Being a Typescript codebase, I updated the configuration to use the `ghost/ts` plugin, which fixed these errors.
=> Fixed eslint config for typescript

compose.yml
no refs
When running with `docker compose up`, the host isn't set to `0.0.0.0`, so the server isn't reachable from localhost. This commit fixes it by setting the host directly when running the command for the proxy-service in compose.
=> Fixed command for docker compose

README.md, compose.ghost.yml, compose.yml, package.json
no refs
This commit adds the ability to easily run the analytics service side-by-side with Ghost running locally in Docker Compose. This provides a more production-like setup when working on the analytics service.
- Ghost's docker compose setup now has a Caddy route handler to route requests to `/.ghost/analytics` to this service.
- This commit adds a new `compose.ghost.yml`, which can be used in addition to the base `compose.yml` to attach the analytics service to the Docker network from the Ghost project.
- It also adds a convenience command: `yarn docker:dev:ghost` and some documentation to the `README.md` for setting this up.
With this setup, Ghost's tracker script will route requests to `http://localhost/.ghost/analytics/tb/web_analytics`. Ghost's Caddy service will route those …
=> Added support for running the analytics service in Ghost's docker compose network

src/services/salt-store/ISaltStore.ts, src/services/salt-store/MemorySaltStore.ts, src/services/salt-store/README.md, src/services/salt-store/SaltStoreFactory.ts, src/services/salt-store/index.ts, test/services/salt-store/MemorySaltStore.test.ts, test/services/salt-store/SaltStoreFactory.test.ts
refs https://linear.app/ghost/issue/PROD-662/analytics-service-should-use-salt-hash-instead-of-storing-the-session
We want to start using a salt + hash fingerprinting method to uniquely and anonymously identify "sessions", rather than persisting session IDs client side in the tracker. This commit adds a `salt-store` service for persisting the salt for each site in an arbitrary persistence layer. By default it uses an in-memory store — this won't work in production since it will be wiped on restarts, but it's sufficient for development and prototyping. 
Once we align on our persistence backend layer for Ghost(Pro) and for self-hosters, we can create stores for them and swap them out easily enough.
=> Added `salt-store` service using adapter pattern for persistence layer

compose.yml, package.json, test/.eslintrc.cjs, test/unit/app.test.ts, test/unit/services/proxy/processors/parse-user-agent.test.ts, test/unit/services/proxy/processors/url-referrer.test.ts, test/unit/services/proxy/processors/user-signature.test.ts, test/unit/services/user-signature/UserSignatureService.test.ts, tsconfig.json, yarn.lock
no refs
My IDE was flagging a lot of type errors in the tests with red squiggles, but they weren't being checked in the `test:types` command, as the tests were excluded. I hate looking at red squiggles, so this commit enables type checking on the test files, but carves out an exception for explicit `any`, since it is often required in tests (i.e. when testing private methods).
=> Added typechecking to test files

src/services/salt-store/FirestoreSaltStore.ts, src/services/salt-store/SaltStoreFactory.ts, test/integration/services/salt-store/FirestoreSaltStore.test.ts, test/unit/services/salt-store/SaltStoreFactory.test.ts
ref https://linear.app/ghost/issue/PROD-662/analytics-service-should-use-salt-hash-instead-of-storing-the-session
The previous implementation would get the Firestore database based on the GCP project ID, but both our staging and production DBs are in the same project, so this won't work. This change allows you to specify a database ID via environment variable, so we can point the analytics service to the correct database.
=> Added databaseId parameter to FirestoreSaltStore

src/services/user-signature/UserSignatureService.ts, test/unit/services/user-signature/UserSignatureService.test.ts
no refs
The user signature generation wasn't consistent for multiple requests from the same browser because we were including a timestamp in the signature, which makes it different for each request and defeats the purpose of a user signature. This removes the timestamp, and also adds the `site_uuid` itself to the signature to prevent cross-site tracking.
=> Fixed the user signature generation

package.json, server.ts, src/app.ts, src/services/salt-store/FirestoreSaltStore.ts, src/utils/index.ts, src/utils/logger.ts, yarn.lock
no refs
Our logs are currently always plain text, which makes the logs difficult to reason about, especially in production. This commit changes the logging config so it's still plain text in development to keep the logs easily human readable, but changes to JSON logs in production to make them more searchable.
=> Reconfigured logging for structured logs in production

compose.yml, docker/firestore/firestore-wrapper.sh, src/services/salt-store/FirestoreSaltStore.ts
no refs
When stopping the compose setup with ctrl+c, the firestore container was using the full 10 second grace period before shutting down, which is annoying. This wraps the command with some basic signal handling so it shuts down immediately.
=> Fixed firestore container slow shutdown

compose.yml, package.json, vite.config.ts, yarn.lock
This reverts commit 401756b4c40392e0e2ef948a30d372e2e998d956.
For some reason this is failing in GCP, despite working locally. Reverting for now to get `main` green again.
=> Revert "Switched from vite to tsc and tsx (#102)"

src/services/salt-store/FirestoreSaltStore.ts
no refs
This function isn't used anywhere, just taking up space, so this commit removes it.
=> Removed unused method on FirestoreSaltStore

CLAUDE.md, src/services/salt-store/FirestoreSaltStore.ts, src/services/salt-store/ISaltStore.ts, src/services/salt-store/MemorySaltStore.ts, src/services/user-signature/UserSignatureService.ts, test/integration/services/salt-store/FirestoreSaltStore.test.ts, test/unit/services/salt-store/MemorySaltStore.test.ts, test/unit/services/user-signature/UserSignatureService.test.ts
ref https://linear.app/ghost/issue/PROD-662/analytics-service-should-use-salt-hash-instead-of-storing-the-session
The user generator service recycles salts every 24 hours, but we currently leave the old salts in the store. This commit adds a simpler scheduler to delete any salts from before the current day UTC.
This can be disabled via config, and probably should be handled more robustly at scale, but this works in development and should be fine for self-hosters, since compose itself doesn't have a native scheduler.
=> Added scheduler to cleanup old salts

src/app.ts, src/utils/logger.ts
no refs
This commit adds more details to the logs in production. Previously the fields included were very limited, to keep the development logs simple, however this inadvertently also limited the production logs so basic things like request method and headers weren't being included — now they are.
=> Improved logs in production

src/app.ts, src/utils/logger.ts
no refs
GCP automatically parses log fields out of the `httpRequest` field. This commit updates the log serialization to match GCP's format, which should make our logs easier to read in GCP's interface.
=> Added log serialization for GCP log parsing

src/app.ts
no refs
This is an attempt to correlate all the logs for a particular request together in GCP. GCP passes a header in all requests with a trace ID, and supposedly if we include it in the logs, it will collapse all the logs from a single request into the top level Cloud Run request log.
=> Added trace context to logs

src/services/proxy/processors/user-signature.ts, test/unit/services/proxy/processors/user-signature.test.ts
no refs
The user signature service was just skipping the signature generation if the site_uuid or ip address were missing. This is incorrect — it should throw an error to prevent sending events to Tinybird without a session id.
=> Improved error handling in user signature service

README.md, compose.yml
Support for running multiple worktrees simultaneously with isolated Docker environments. Each worktree can now run its own development server, tests, and services without port conflicts or container name collisions.
The previous Docker setup used hardcoded ports and project names, making it impossible to run multiple worktrees simultaneously. This created bottlenecks for developers wanting to work on multiple features in parallel.
Modified compose.yml to use environment variables for port configuration and leverage COMPOSE_PROJECT_NAME for automatic container isolation. Added comprehensive documentation with setup examples for different worktree configurations.
Enables true parallel development workflows where developers can have multiple isolated environments running simultaneously …
=> Added multi-worktree Docker Compose support for parallel development

compose.yml
For batching events, we're planning to use GCP Pub/Sub. This commit sets up an emulator running in docker compose so we can test event batching locally.
=> Added pub/sub emulator to compose

package.json
no refs
The `yarn ship` command tries to run tests first because of this `yarn preship` script. This step isn't really necessary, since we're not directly shipping from our local checkout, but rather raising a PR, which will need to pass tests before merging anyways.
=> Removed the preship command

package.json, scripts/.eslintrc.cjs, scripts/ship.js
no refs
The `yarn ship` script threw an error when trying to pull the latest changes from `upstream/main` — this adds a fallback if `upstream/main` (or `origin/main` if $GHOST_UPSTREAM isn't set) doesn't exist locally for whatever reason. It also adds an eslint config for the scripts directory and fixes the linter errors.
=> Fixed ship script rev-parse command error

scripts/ship.js
no refs
The `ship.js` script had hardcoded `git push origin main` instead of using `$GHOST_UPSTREAM` if it's set. I have it set as `upstream` so it was failing. It will now use $GHOST_UPSTREAM if set, and fallback to origin.
=> Fixed remote in git push command to use $GHOST_UPSTREAM

scripts/ship.js
no refs
Keeping the auto-generated release commit message succinct, it will just be `vX.X.X` now
=> Modified autogenerated release commit message

.github/workflows/build.yml
no refs
With this change, commits to main will always deploy to staging, but they will only deploy to production if the version number has changed. Also, if the version number changes, the workflow will tag the commit.
=> Updated deploy workflow to only ship to production if the version has changed

.github/actions/lint-and-test/compose.ci.yml, package.json, src/services/events/publisher.ts, test/integration/services/events/publisher.test.ts, yarn.lock
To publish events to GCP pub/sub, we'll need an event publisher. This adds a very basic publisher with a `publishEvent` function, and adds integration tests that run against a pub/sub emulator in docker compose.
=> Added event publisher with integration tests

.github/actions/lint-and-test/compose.ci.yml, compose.yml, docker/pubsub/start-pubsub.sh, src/services/proxy/proxy.ts, src/utils/logger.ts, test/integration/app.test.ts
This commit is the smallest change to test out publishing to our new GCP Pub/Sub topic in staging and production. It publishes events the topic on every request, and continues to forward the requests to Tinybird as usual.
=> Added event publishing to ingestion endpoint

.env.example, .github/actions/lint-and-test/compose.ci.yml, README.md, compose.yml, docker/pubsub/start-pubsub.sh, src/services/events/publisher.ts, src/services/salt-store/SaltStoreFactory.ts, test/integration/app.test.ts, test/integration/services/events/publisher.test.ts, test/unit/services/salt-store/SaltStoreFactory.test.ts
no refs
Cloud Run automatically passes the project id to the service via the `GOOGLE_CLOUD_PROJECT` environment variable. The application was using multiple difference service-specific variables for this value, e.g. `FIRESTORE_PROJECT_ID`, which isn't necessary and adds confusion and configuration complexity.
This change harmonizes this everywhere, so we always just use `GOOGLE_CLOUD_PROJECT` — this way we don't have to pass the same value to our service multiple times in staging/production.
=> Switched all references to GCP project ID to the default variable

src/services/proxy/proxy.ts, test/integration/app.test.ts
no refs
Previously this was publishing the fully processed event, but the intent here is to publish the raw event exactly as it comes in from the HTTP request. Processing will happen downstream in a subscriber.
=> Modified event publishing to publish unprocessed event

src/app.ts, test/integration/app.test.ts
Since we added the `x-site-uuid` header from Ghost, the requests from the `ghost-stats` script have been failing due to a CORS error:
```
main.ghost.org/:1 Access to fetch at 'https://traffic-analytics.ghostinfra.net/tb/web_analytics?name=analytics_events&token=p.eyJ1IjogIjVhOWRjMjQ1LWQyNjEtNGU4MC05ZDYzLWY4ZTliOTNhY2I3NCIsICJpZCI6ICIyNTQ5ZmZhYy1mZDZjLTQ5NmUtOTU4Ny1jZTgxOGE1MDlmNDkiLCAiaG9zdCI6ICJldV9zaGFyZWQifQ.5sfIJ7JYTGdXMsvP7AkbzcbHXBCIHPtcxUaGsAJaDMA' from origin 'https://main.ghost.org' has been blocked by CORS policy: Request header field x-site-uuid is not allowed by Access-Control-Allow-Headers in preflight response.
```
This commit should fix this error, by adding the `x-site-uuid` header to the list of allowed headers in the fastifyCors configuration.
=> Fixed CORS error due to x-site-uuid header

package.json, src/app.ts, src/plugins/logging.ts, yarn.lock
We've been adding lots of functionality to the main `app.ts` file and it's beginning to get a little hard to follow. In Fastify, it's a common pattern to extract functionality into plugins, and register them in the main app. This commit is the first move in this direction, pulling out the logging hooks specifically into their own plugin.
=> Extracted logging hooks into a fastify plugin

.gitignore, README.md, config.example.json, config.testing.json, package.json, server.ts, src/app.ts, src/services/events/publisher.ts, src/services/proxy/proxy.ts, src/services/salt-store/SaltStoreFactory.ts, src/services/user-signature/UserSignatureService.ts, src/types/config.d.ts, src/utils/logger.ts, test/unit/services/salt-store/SaltStoreFactory.test.ts, test/unit/services/user-signature/UserSignatureService.test.ts, test/utils/config-mock.ts, yarn.lock
This project has been using regular environment variables for all configuration prior to now. To maintain consistency with our other projects, we should aim to use established libraries when available. This updates all uses of `process.env` to use `config.get()` instead, except for specifically checking `NODE_ENV`. 
For now it maintains backwards compatibility — all the config keys are the same as the environment variables were, which means all caps and no nesting. We might want to change this eventually to take advantage of nested config, but that will require some changes to our staging/production environments as well. For now this should be sufficient.
=> Added `@tryghost/config` for configuration

scripts/setup-worktree.sh
When working with multiple worktrees, we need to avoid port conflicts. This is done by setting the ports in a .env file manually for each worktree. This is tedious to do manually, so this script helps automate it. 
Running `./scripts/setup-worktree.sh {OFFSET}` will generate a new .env file, which calculates the appropriate ports for each service based on the provided integer OFFSET, and set the COMPOSE_PROJECT_NAME appropriately to avoid conflicts with other worktrees.
=> Added setup-worktree script to help automate setting up new worktrees

.github/workflows/healthchecks.yml
There is a change in Ghost required before these checks will pass. This hasn't yet been deployed to production, so these will fail every time. Removing these checks for now.
=> Removed production site from healthchecks

.github/workflows/healthchecks.yml, playwright.config.ts
So we know when they fail. We'll probably want this to trigger an ops genie alert or an incident in the future, at least if they fail in production, but for now a Slack notification should suffice.
=> Added slack notification to the healthchecks job

.github/workflows/build.yml
Right now the only way to know that a deployment failed is to remember to check Github or GCP after it runs. This commit adds a notification into the #feed-traffic-analytics channel in Slack for all deployments with an indication of whether it succeeded or failed.
=> Added deployment notifications to build pipeline

src/app.ts, src/plugins/proxy.ts
The `/local-proxy` endpoint is closely coupled with the proxy itself, so this commit moves it into the proxy plugin along with the main proxy endpoint.
=> Moved the local-proxy endpoint into the proxy plugin

playwright.config.ts
The healthchecks are failing ~50% of the time on staging, but we don't have the full traces when they run in CI, which makes it hard to debug them. This should add the full trace so we can inspect the DOM, console, network requests, etc. when failures occur.
=> Added playwright traces for failing healthchecks

.github/workflows/healthchecks.yml
The healthcheck workflow was installing Playwright browsers from scratch on every run, causing unnecessary delays and bandwidth usage. This made the hourly healthchecks slower than needed and wasted CI resources.
Added browser caching based on Playwright version to skip reinstallation when browsers are already available. Also consolidated duplicate artifact upload steps into a single upload. This will reduce workflow execution time from ~3 minutes to ~30 seconds for subsequent runs.
=> Optimized healthcheck workflow with Playwright browser caching

.github/workflows/healthchecks.yml
The playwright caching step was failing due to some kind of formatting error from GHA. This uses a different approach to get the current playwright version, which fixes the error and allows the workflow to complete successfully.
=> Fixed playwright caching in healthchecks workflow

.github/workflows/healthchecks.yml, test/healthchecks/ghost-site.spec.ts
This switches to using dedicated test sites on staging, rather than pointing to main.ghost.org. It covers a few different scenarios as well to ensure we haven't broken event ingestion for certain types of sites.
- Site without custom domain
- Site with custom domain
- Site with subdirectory
=> Added 3 staging sites to healthchecks

.github/workflows/build.yml
Our CI pipeline wasn't setup to deploy new revisions to our worker Cloud Run service, only the main analytics service. This adds a deployment step for the worker service for production and staging, and changes how the Slack notifications work to avoid duplicate notifications for each deployment.
=> Updated deployment pipeline to also deploy worker to Cloud Run

.github/workflows/build.yml
We have some basic liveness probes setup in GCP to ensure that deployments start up, but we don't have comprehensive checks to make sure the deployment is handling requests from Ghost properly. This commit runs our healthchecks on each environment right after a deployment succeeds, to ensure that the core functionality hasn't been broken by the deployment.
=> Setup healthchecks to run after deployments

src/schemas/v1/page-hit-raw-request.ts, src/types/index.ts, test/e2e/web_analytics.test.ts, test/unit/schemas/v1/page-hit-raw-request.test.ts
After deploying https://github.com/TryGhost/TrafficAnalytics/commit/48897f59133e8211ef53bcbbdf6e0f1653e25547 to staging, the healthchecks failed with a 400 response. The requests sent `location` with a `null` value, which apparently can happen and should be allowed (for now at least). This updates the schema to allow it.
=> Updated schema to allow `null` for location

package.json, src/plugins/proxy.ts, src/schemas/v1/page-hit-raw-request.ts, yarn.lock
The `@fastify/http-proxy` plugin we were using was overly complex for our needs — it's designed to be used as a fully fledged proxy server for handling multiple routes with complex logic. It's ultimately built on `@fastify/reply-from`, which is a plugin for forwarding a single request/endpoint to an upstream server.
Really all we need is `@fastify/reply-from`, and this also gives us more control over the request handling — this will make it a lot easier to conditionally proxy the request or simply publish the event to pub/sub. It also allows us to take advantage of Fastify's built in request validation using JSON schema since we are now defining our route directory.
=> Refactored proxy endpoint to use `@fastify/reply-from` instead of `@fastify/http-proxy`

package.json, src/plugins/proxy.ts, src/schemas/v1/page-hit-raw-request.ts, yarn.lock
This reverts the refactor from http-proxy to reply-from. I think we should do this, but I don't have enough confidence in our e2e tests just yet to roll this out. I'll improve our tests using wiremock before making this change.
This reverts commit 8932b6161a0d9df6039f972df8af600757f266fe.
=> Revert "Refactored proxy endpoint to use `@fastify/reply-from` instead of `@fastify/http-proxy`"

compose.yml, test/e2e/web_analytics.test.ts, test/utils/wiremock.ts
Our current e2e tests we're not fully testing that we are sending the right data to Tinybird. This commit sets up wiremock in place of our `/local-proxy` endpoint, so we can not only check the response we get from our own fake endpoint, but also make assertions on the data we're sending to the `PROXY_TARGET`.
=> Added wiremock for e2e testing

.github/actions/lint-and-test/action.yml, .github/actions/lint-and-test/compose.ci.yml, compose.override.yml, compose.yml, package.json
Currently our main `compose.yml` and our `compose.ci.yml` are two completely different files, which is a pain to maintain and can lead to drift between our local dev environment and our CI environment. This changes to using a base `compose.yml` for both environments, with a `compose.override.yml` for local development (to add bind mounts and volumes for local development) and a `compose.ci.yml` which only includes overrides for the CI environment.
This should help prevent issues where tests pass locally but not in CI, and make it easier to maintain these two environments, which are 99% shared configuration.
=> Refactored compose files to improve parity between local and CI

.github/actions/lint-and-test/action.yml, .github/actions/lint-and-test/compose.ci.yml, compose.override.yml, compose.yml, package.json, test/e2e/web_analytics.test.ts
Currently our e2e tests only run locally against the services running in docker compose. In CI, we don't ever install the node dependencies except in the Docker image itself, so in order to run the e2e tests in CI we'll need to modify the e2e tests to be able to run in docker compose. 
This adds a new e2e-test service to our `compose.yml` file and makes the required changes to the e2e test suite to be able to run in this environment. This way we can run the e2e tests locally with `docker compose run --rm e2e-test` (or `yarn docker:test:e2e`). It also paves the way to running these tests in CI.
=> Added e2e tests to CI

src/schemas/v1/index.ts, src/schemas/v1/page-hit-raw.ts, test/unit/schemas/v1/page-hit-raw.test.ts
We're currently publishing messages to pub/sub for all incoming requests that pass validation. However, we're not passing all the data that we need to in the message, and we're also passing some data that we definitely don't need. This commit adds a JSON Schema for the `page-hits-raw` events, which we can use to validate the messages before publishing to the topic, and when receiving them from the topic.
Next up: change the payload that we're actually publishing to pub/sub, according to this schema.
=> Added page-hits-raw schema for pub/sub messages

.github/actions/lint-and-test/action.yml, .github/actions/lint-and-test/compose.ci.yml, Dockerfile, compose.yml, package.json
The e2e tests were a bit flaky in CI — the e2e-test service was running before the analytics-service was fully healthy. This commit adds a healthcheck to the analytics-service and the worker, and force the e2e-test service to wait for both services to be healthy before running.
=> Fixed flaky e2e tests in CI

src/schemas/v1/page-hit-processed.ts, src/services/batch-worker/BatchWorker.ts, test/unit/schemas/v1/page-hit-processed.test.ts, test/unit/services/batch-worker/batch-worker.test.ts
We're currently receiving and validating the raw page hit messages in the worker process. This adds a page-hit-processed schema, including transform functions to accept a pageHitRaw and output a pageHitProcessed. 
It adds the processing to the BatchWorker and logs the result for now. Next step is to send these events to the `analytics_events_test` datasource in Tinybird, then start batching them.
=> Added page-hit-processed schema and transforms

src/services/salt-store/FirestoreSaltStore.ts
This health check has failed in staging, but the logs don't provide much info. This should provide more information in the error logs.
=> Improved logging for FirestoreSaltStore health check failures

src/services/proxy/processors/user-signature.ts, test/unit/services/proxy/processors/user-signature.test.ts
We've seen a growing number of "Failed to generate user signature" log messages, but they don't include the full error because this log was formed incorrectly. This should fix the logging so we can see the full error message when generating the user-signature fails.
=> Improved logging for "Failed to generate user signature" message

src/schemas/v1/page-hit-processed.ts, test/unit/schemas/v1/page-hit-processed.test.ts
The events sent from the batch worker, which have gone through the schema-based pipeline were ending up in Tinybird's quarantined rows, because they didn't have the `payload.site_uuid` key. This adds the `site_uuid` to the payload, so it will pass Tinybird's ingestion validation.
=> Added `site_uuid` to payload in page-hit-processed schema

src/schemas/format-registry.ts, src/schemas/index.ts, src/schemas/v1/incoming-event-request.ts, src/schemas/v1/index.ts, src/schemas/v1/page-hit-processed.ts, src/schemas/v1/page-hit-raw.ts, src/services/batch-worker/BatchWorker.ts, src/services/proxy/proxy.ts, test/unit/schemas/v1/incoming-event-request.test.ts, test/unit/schemas/v1/page-hit-processed.test.ts, test/unit/schemas/v1/page-hit-raw.test.ts
The `FormatRegistry` calls allow Typebox to enforce validation rules for specific formats like `uuid` without having to reinvent the wheel for each field. We were registering all the formats within each schema, which needlessly duplicated this code. 
This consolidates all our `FormatRegistry` calls into `schemas/format-registry.ts` and runs it in `schema/index.ts`. This ensures the formats are registered for all our Schemas, so we can just use the formats in the schema files themselves without having to explicitly register them in each schema.
=> Deduplicated the `FormatRegistry` TypeBox calls from the schema files

src/schemas/v1/incoming-event-request.ts, src/schemas/v1/page-hit-processed.ts, src/schemas/v1/page-hit-raw.ts, src/services/proxy/proxy.ts, src/types/index.ts, test/unit/schemas/v1/incoming-event-request.test.ts, test/unit/schemas/v1/page-hit-raw.test.ts
The `ghost-stats` script no longer sends the `referrer` field directly, instead sending a `parsedReferrer` object. This service treats the referrer as a required value, and therefore any requests from the `ghost-stats` script are failing the validation, and thus not ending up in Tinybird.
This commit makes the referrer field optional, and adds an optional `parsedReferrer` field, so that these requests should pass validation and succeed.
=> Fixed referrer validation failing

src/schemas/v1/page-hit-processed.ts, test/unit/schemas/v1/page-hit-processed.test.ts
Currently the proxy path is sending along the `user-agent` field in the payload, while the batching path is not. This adds the user-agent to the page-hits-processed schema so that it's included in the payload that's sent to Tinybird. We will likely want to remove this soon, but for now this keeps the two paths in sync so we can validate that they are the same.
=> Added user-agent to page-hit-processed schema

src/schemas/v1/page-hit-processed.ts, test/unit/schemas/v1/page-hit-processed.test.ts
The referrer fields in the page-hit-processed schema didn't quite match up with the current behavior from the proxy endpoint. This updates the schema to match, such that the events landing in `analytics_events` from the proxy should be identical to those landing in `analytics_events_test`.
=> Updated referrer fields in schema to match the proxy

src/services/batch-worker/BatchWorker.ts, test/unit/services/batch-worker/batch-worker.test.ts
When a POST request to Tinybird from the batch worker fails (for whatever reason, ie `EHOSTUNREACH` errors), the batch worker is catching the error, logging it then rethrowing it and crashing.  These transient errors will always happen, so we definitely don't want to rethrow this error and crash. 
This removes the rethrow — we're nacking the message so it will be retried, and this allows the worker to keep processing messages without interruption.
=> Fixed batch worker throwing error when POST request fails

src/schemas/v1/incoming-event-request.ts, src/schemas/v1/page-hit-processed.ts, src/schemas/v1/page-hit-raw.ts, src/services/proxy/proxy.ts, test/unit/schemas/v1/page-hit-processed.test.ts, test/unit/schemas/v1/page-hit-raw.test.ts, test/unit/services/batch-worker/batch-worker.test.ts, test/unit/services/proxy/proxy.test.ts
Having a unique identifier for each event will come in handy for debugging, and is currently useful for correlating events sent to `analytics_events` and `analytics_events_test` for validating the batch worker processing.
=> Added optional `event_id` field to payload in schemas

compose.yml, package.json, src/plugins/proxy.ts, src/schemas/v1/incoming-event-request.ts, src/services/proxy/index.ts, src/services/proxy/proxy.ts, yarn.lock
This gives us much more flexibility in how we define our routes, and to use conditional logic within the route to e.g. route directly to Tinybird, or to publish to pub/sub
=> Removed `fastify-http-proxy` in favor of `fastify-reply-from`

scripts/send-test-request.sh, src/plugins/proxy.ts, src/schemas/v1/index.ts, src/schemas/v1/page-hit-request.ts, src/services/proxy/proxy.ts, test/unit/schemas/v1/page-hit-request.test.ts
Currently the endpoint we're serving the proxy on is `/tb/web_analytics`. Soon we'll be renaming this to something like `/api/v1/page_hit` to make it more explicit what it's for. In the future we may have other event types with their own endpoints and schemas, so `incoming-event-request` feels far too generic.
=> Renamed `incoming-event-request` schema to `page-hit-request` schema

src/plugins/proxy.ts, test/integration/app.test.ts
ref https://linear.app/ghost/issue/PROD-1961/remove-the-tracker-token-from-ghost-config-and-tracker-script
We ultimately don't want the tracker token to come from Ghost, since this exposes it in the browser. This commit overrides the tracker token in the request by stripping the existing token from the url query parameters if provided, and adding the `TINYBIRD_TRACKER_TOKEN` from environment as an authorization bearer token.
=> Added tracker token override if provided in environment

compose.yml, test/e2e/web_analytics.test.ts, test/utils/wiremock.ts
The assertions in the e2e tests were too generic, using `url.includes()` to check the passed query parameters. This isn't specific enough to catch the difference between `analytics_events` and `analytics_events_test`, and was resulting in false failures. This cleans that up, and also adds a default value to the test token in case a token isn't provided via environment variable.
=> Improved assertions in e2e tests and removed unnecessary tests

src/app.ts, src/utils/validation-error-handler.ts, test/integration/validation-error-logging.test.ts
We're seeing an increase in validation errors over the last few days, but our logs don't show the reason for the errors. We should relax the validation rules to be much more liberal in what we accept, but in order to do so we also need more visibility into what we're currently rejecting.
=> Added more thorough logging for validation errors

src/schemas/v1/page-hit-processed.ts, src/schemas/v1/page-hit-raw.ts, test/unit/schemas/v1/page-hit-processed.test.ts
The referrer parsing in batch mode didn't quite match up with the referrer parsing in proxy mode. This updates the `transformReferrer` function to match the logic in the `processReferrer` function. This should align the result of the two different pipelines perfectly, at which point we can re-merge them.
=> Fixed referrer parser drift between proxy and batch mode

src/schemas/v1/page-hit-processed.ts, test/unit/schemas/v1/page-hit-processed.test.ts
The `transformPageHitRawToProcessed` function is now correctly adding the `referrerUrl`, `referrerSource` and `referrerMedium` to the payload, but it was leaving the legacy `referrer` and `parsedReferrer` fields in the object. 
This removes them, to avoid any ambiguity in what the actual referrer info is.
=> Removed parsedReferrer and referrer from page-hit-processed schema

src/schemas/v1/page-hit-processed.ts, test/unit/schemas/v1/page-hit-processed.test.ts
The `parsedReferrer` values are exactly what was sent to the analytics service. Even though we parse the values out into `referrerUrl`, `referrerSource`, `referrerMedium`, it could prove useful to have the original values sent to the service in the payload in the future for debugging. This adds the `parsedReferrer` values back to the payload if they were provided.
=> Readded parsed referrer to payload

src/services/proxy/processors/url-referrer.ts, test/unit/services/proxy/processors/url-referrer.test.ts
ref https://github.com/TryGhost/TrafficAnalytics/commit/71d2a5a775525bb1a2363b164d6b96052ab5c1f2
This does the same thing as the commit above, but for the direct proxy processing pipeline. This way we maintain the parsedReferrer in the payload for debugging, in case we run into any issues with the processing of the referrers in the future.
=> Added parsed referrer to payload from proxy

src/plugins/proxy.ts, src/plugins/worker-plugin.ts, test/e2e/web_analytics.test.ts, test/integration/app.test.ts
Now that the pipelines are confidently publishing the same data to Tinybird, we should stop running both in parallel and switch over completely to the batch worker. This commit makes the strategy configurable, currently based on whether the pub/sub topic environment variable is configured. We'll probably want to change this to be more explicit eventually, but for now it meets our needs just fine.
=> Switched to using batch mode only if pub/sub topic is configured

.husky/pre-commit, package.json, yarn.lock
This commit adds a pre-commit hook, which will run `yarn lint` and `yarn test:unit` before allowing commits to go through, which helps prevent wasted time with CI. 
The hooks are opt-in, by setting the `ENABLE_PRE_COMMIT_HOOKS` environment variable in your shell to `true`.
=> Added opt-in pre-commit hooks to run unit tests and linting

src/app.ts, src/plugins/proxy.ts, src/transformations/page-hit-transformations.ts, test/unit/transformations/page-hit-transformations.test.ts
Starting to pull all transformations into a single place in the codebase for easier testing and better separation of concerns. Right now some of these files are sprinkled throughout the proxy plugin itself and the schemas, when really they should be in their own dedicated area.
=> Extracted `pageHitRawPayloadFromRequest` transformation into its own file

test/healthchecks/ghost-site.spec.ts
After changing Ghost's configuration to use the new `/api/v1/page_hit` endpoints, our healthchecks started failing because they are specifically looking for the request to `/.ghost/analytics/tb/web_analytics`, and those requests are no longer being made. 
This updates the healthchecks to just look for any request to `/.ghost/analytics/**` for now so they will pass for either endpoint. I'll circle back and make these more specific after the change is fully rolled out.
=> Updated healthchecks to be compatible with new versioned endpoint

src/services/batch-worker/BatchWorker.ts, src/services/salt-store/FileSaltStore.ts, src/services/salt-store/FirestoreSaltStore.ts
no ref
The logging serializer expects `err` instead of `error`, so we were getting blank object notation `{}` in error logs locally.
=> Refactored error logging to use 'err' key instead of 'error'

renovate.json
To avoid any regressions between QA complete and 6.0 launch, this prevents renovate from automatically merging any dependency updates. We will undo this change next week.
=> Disable renovate automerge for all packages during code freeze

src/services/batch-worker/BatchWorker.ts, test/unit/services/batch-worker/batch-worker.test.ts
Our current logging in the batch worker doesn't fully take advantage of structured logging, which makes it difficult to debug when messages fail to be processed for whatever reason. This commit doesn't change any behavior apart from logging:
- Removes duplicate error logs when a message fails to be parsed successfully
- Adds an `event` field to all relevant logs to make them more searchable
- Adds the pub/sub message ID and message data to all relevant logs
=> Improved structured logging in the batch worker

src/schemas/v1/page-hit-request.ts, test/integration/app.test.ts
Currently a request with a whitespace-only user agent header, i.e. `User-Agent:  ` can pass validation. This causes errors downstream in the `BatchWorker`, which ends up trying to process a message with an empty user agent. 
This fixes the problem with the request validation, which should prevent these invalid events from reaching the `BatchWorker`. It does not yet improve the handling in the `BatchWorker` itself.
=> Fixed validation incorrectly passing with whitespace-only user agent

Dockerfile, README.md, compose.ghost.yml, compose.yml, package.json, scripts/entrypoint.sh
This makes it much easier to run Ghost locally against your local clone of the Analytics Service. 
Related PR in Ghost: https://github.com/TryGhost/Ghost/pull/24731
Key changes:
- Adds a `compose.ghost.yml` file, which attaches the analytics service to the Ghost project's default network and mounts the `shared-config` volume at `/mnt/shared-config`
- Adds a `yarn dev:ghost` command that extends the base `compose.yml` with `compose.ghost.yml`
- Adds an entrypoint to the analytics service that gets the `TINYBIRD_TRACKER_TOKEN` from the volume on boot
=> Improved support for running locally with Ghost

.github/actions/run-healthchecks/action.yml, test/healthchecks/ghost-site.spec.ts
ref PROD-2547
ref https://linear.app/ghost/issue/PROD-2547/improve-ci-health-check-reliability
Sometimes installing dependencies for playwright can be super slow or even fail. This switches to use the prebuilt docker image instead to improve the speed and reliability.
=> Updated health checks to run via docker
